### ISSUE TITLE
test script hard-codes 8001 and does not take an argument

### ISSUE THREAD

**Issue by turkeylurkey** [makotogo/developerWorks#1]
In the youtube video you say that the script test-k8sdemo.sh takes an argument but it seems only to access the host at port 8001. This is an issue as you suggest to use port 8080 throughout the tutorial. 

When you run the script it prints: 
curl: (7) Failed to connect to localhost port 8001: Connection refused
If you change 8001 in the script to $1 then it prints:
****************************
* Greetings from the DEMO! *
****************************

(BTW Thanks for the education. )

**Comment by makotogo** [comment]
Hey @turkeylurkey. Sorry about that. I forgot to commit the change that makes the script argument work.

Please grab the latest, and try again. Thanks for reporting this!

--jsp
