### ISSUE TITLE
app keeps on crashing after aftering tapping the connect button,

### ISSUE THREAD

**Issue by namespace7** [makotogo/developerWorks#13]
the app keeps on crashing after aftering tapping the connect button, i'm using Emulator which has api number 24 ,anything wrong with that?
the flow diagram shows no errors!

**Comment by jstevenperry** [comment]
It's very possible that something changed in the Android API and is causing a `NullPointerException` now. I'll look at it ASAP.

**Comment by riferman** [comment]
Hello, when can we expect a bug fix?

**Comment by namespace7** [comment]
Still clueless , it doesn't so any warning or error other then shutting
down itself! Did you guys tested on the phone with api 20+?
