### ISSUE TITLE
Error trying login and get user Context. Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ECONNREFUSED 127.0.0.1:7054]

### ISSUE THREAD

**Issue by simonmullaney** [makotogo/developerWorks#2]
Hello,

I was following your youtube video on this - which was great!

I had one issue though, I set up a persistent and secured REST server using Docker for a hyperledger composer business network as of this tutorial: https://hyperledger.github.io/composer/integrating/deploying-the-rest-server.html

But then when I try to carry out transactions on the rest server I get the following error:

```
Unhandled error for request GET /api/Contract: Error: Error trying login and get user Context. Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ECONNREFUSED 127.0.0.1:7054]
```

I think it has something to do with running my rest server in my docker container....

My connection.json file -> (/Users/simonmullaney/.composer/cards/admin@block-aviation-network/connection.json)

```
Simons-MacBook-Pro:admin@block-aviation-network simonmullaney$ cat connection.json 
{"name":"hlfv1","type":"hlfv1","orderers":[{"url":"grpc://192.168.0.4:7050"}],"ca":{"url":"http://192.168.0.4:7054","name":"ca.org1.example.com"},"peers":[{"requestURL":"grpc://192.168.0.4:7051","eventURL":"grpc://192.168.0.4:7053"}],"channel":"composerchannel","mspID":"Org1MSP","timeout":300}
```
Where 192.168.0.4 is the ip address of my laptop:
```
 ifconfig |grep inet
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	inet6 fe80::c36:5cca:eba0:4cd6%en0 prefixlen 64 secured scopeid 0x5 
	inet6 fd88:2653:8db2::1444:96fc:5308:61af prefixlen 64 autoconf secured 
	inet6 fd88:2653:8db2::e5af:caa4:ff41:bd00 prefixlen 64 autoconf temporary 
	inet 192.168.0.4 netmask 0xffffff00 broadcast 192.168.0.255
	inet6 fe80::a4e8:b6ff:fe2b:f94f%awdl0 prefixlen 64 scopeid 0x7 
	inet6 fe80::8be9:ba07:4886:2721%utun0 prefixlen 64 scopeid 0xb 
```

Do you have any idea what could be wrong?

**Comment by makotogo** [comment]
Hi @simonmullaney 

Thanks for reading. Unfortunately, there are so many things it could be I'm afraid that guessing would not prove to be productive.

That said, I did notice that the card you reference above is not from the tutorial network, but one called `block-aviation-network`. I would start there.

I made very effort to test the code and instructions thoroughly before publication (nothing irritates me more than tutorials that are inaccurate or just don't work). If followed carefully you should have no problems getting this code to work. I encourage you to nuke your local environment and start over from scratch and follow the instructions carefully.

Good luck!

--jsp

**Comment by simonmullaney** [comment]
Thanks @makotogo
